"""Initial migration.

Revision ID: 462977a9a8c7
Revises: 
Create Date: 2024-05-17 09:58:47.065422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '462977a9a8c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('siteurl', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('businesstype', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('createdat', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sites_pkey'),
    sa.UniqueConstraint('siteurl', name='sites_siteurl_key')
    )
    # ### end Alembic commands ###
